FROM node:22.19-bookworm-slim

ARG UID=1000
ARG GID=1000

RUN (getent passwd ${UID} && /usr/sbin/userdel -r $(getent passwd ${UID} | cut -d: -f1) || true) && \
  (getent group ${GID} || /usr/sbin/groupadd -g ${GID} nonroot) && \
  /usr/sbin/useradd -u ${UID} -g ${GID} -m -s /bin/bash nonroot

COPY --chmod=755 ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

USER nonroot
WORKDIR /app

EXPOSE 3000

CMD ["npm", "run", "dev"]

